"""
Default constants for inference operations
"""

INFERENCE_TEMPERATURE = 0.01
INFERENCE_MAX_TOKENS = 8192
INFERENCE_MAX_TOOL_ITERATIONS = 5
INFERENCE_API_TIMEOUT = 120  # seconds

INFERENCE_API_RETRY_ATTEMPTS = 3
INFERENCE_API_RETRY_DELAY = 5.0  # seconds
INFERENCE_API_MAX_RETRY_DELAY = 60.0  # seconds
INFERENCE_API_RETRY_BACKOFF_MULTIPLIER = 2.0
